### ISSUE TITLE
Pre-trained models

### ISSUE THREAD

**Issue by schliffen** [CASIA-IVA-Lab/ZBS#1]
it would be very helpful if pretrained models were available for bench-marking

**Comment by AAAAAAAyq** [comment]
> it would be very helpful if pretrained models were available for bench-marking

Our approach uses directly the official pre-trained models provided by [Detic](https://github.com/facebookresearch/Detic), the code below will allow to download one of them. 

```
mkdir models
wget https://dl.fbaipublicfiles.com/detic/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth -O models/Detic_LCOCOI21k_CLIP_SwinB_896b32_4x_ft4x_max-size.pth
```

More details can be found in MODEL ZOO in [GET_STARTED.md](https://github.com/CASIA-IVA-Lab/ZBS/blob/main/docs/GET_STARTED.md).
